name: Template Library BuildId Branch

on:
    schedule:
        - cron: "0 */6 * * *"
    workflow_dispatch:

permissions:
    contents: write

jobs:
    check-and-branch:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"

            - name: Install SteamCMD (manual)
              run: |
                  set -e
                  sudo apt-get update
                  sudo apt-get install -y ca-certificates lib32gcc-s1 curl tar
                  mkdir -p "$HOME/steamcmd"
                  curl -sSL https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz -o steamcmd_linux.tar.gz
                  tar -xzf steamcmd_linux.tar.gz -C "$HOME/steamcmd"
                  echo "STEAMCMD=$HOME/steamcmd/steamcmd.sh" >> $GITHUB_ENV

            - name: Fetch current build IDs
              run: node TemplateLibraryGenerator/scripts/steam_buildids.js --steamcmd "$STEAMCMD" > current_buildids.json

            - name: Decide update
              id: decide
              run: |
                  OUT=$(node TemplateLibraryGenerator/scripts/decide_update.js --from-file ./current_buildids.json --dry-run --decision-only)
                  echo "decision=$OUT" >> $GITHUB_OUTPUT
                  if [ "$OUT" != "NO_UPDATE" ]; then
                    ID=$(node -e "const fs=require('fs'); const cur=JSON.parse(fs.readFileSync('current_buildids.json','utf8')); let id=0; if('public' in cur){ id=Number(cur.public)||0; } else { for (const v of Object.values(cur)) { const n=Number(v)||0; if(n>id) id=n; } } process.stdout.write(String(id));")
                    echo "branchid=$ID" >> $GITHUB_OUTPUT
                  fi

            - name: Create branch and commit
              if: steps.decide.outputs.decision != 'NO_UPDATE'
              run: |
                  set -e
                  BRANCH_NAME="update/build-${{ steps.decide.outputs.branchid }}"
                  git config user.name "github-actions[bot]"
                  git config user.email "github-actions[bot]@users.noreply.github.com"
                  git checkout -b "$BRANCH_NAME"
                  # Clean up CI artifacts we don't want to commit
                  rm -f current_buildids.json steamcmd_linux.tar.gz || true
                  git add TemplateLibraryGenerator/data/last_buildids.json
                  # Commit only if there are staged changes
                  if git diff --cached --quiet; then
                    echo "No changes to commit after update; exiting."
                    exit 0
                  fi
                  git commit -m "Update last_buildids.json for build ${{ steps.decide.outputs.branchid }}"
                  git push --set-upstream origin "$BRANCH_NAME"
